### ISSUE TITLE
Add edit role to service account of the Tekton build

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#108]
## Issue

When `no edit role` is assigned to the `ServiceAccount build-bot` of the Tekton user, then we get this error during `buildah push`

```
error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/lib/shared,overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mountopt=nodev,metacopy=on]image-registry.openshift-image-registry.svc:5000/test/fruit-client-sb:latest" to "docker://image-registry.openshift-image-registry.svc:5000/test/fruit-client-sb:latest": Error writing blob: Error initiating layer upload to /v2/test/fruit-client-sb/blobs/uploads/ in image-registry.openshift-image-registry.svc:5000: unauthorized: authentication required
```
This is because the service account wasn't authorized to push to the registry.

## Todo

Add edit role to service account of the Tekton build

```
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: edit
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
    - kind: ServiceAccount
      name: build-bot
```

**Comment by cmoulliard** [comment]
This new rule should resolve the problem

```
    - apiGroups:
      - ""
      - image.openshift.io
      resources:
      - imagestreams/layers
      verbs:
      - get
      - update
```

**Comment by cmoulliard** [comment]
Correct rule is 

```
    - apiGroups:
      - ""
      - image.openshift.io
      resources:
        - imagestreams
        - imagestreams/layers
      verbs:
      - '*'
```

Result
```
Getting image source signatures
Copying blob sha256:fb15b60ae93220334096891a970266fad8dbd924c154310edefdb87e20ccc272
Copying blob sha256:831a05810227c179b57ecfaaccefa54c547c437661948b072a78032f265ceed2
Copying blob sha256:b4aefd102d30697dbb14b2c08dfc616dab3a98cee461ebaeead36158b0271470
Copying blob sha256:2411e39d1cd02a52d9ad8d262362e9dcfc73bcd5cc188c10970080f82e6f57aa
Copying blob sha256:e9300633a9ba3610939733a35a62e05a5276e21ad0d087ec9a536c3163b3761d
Copying blob sha256:050c734bd2868bcd3b69ab0ca033aa3bc95a00a4a1e5317e732394e1c36ef59e
Copying blob sha256:0a30adecd7a4c8fb75a87f72659fee86f32299f47277b6d4f6c3bec29f82ae2c
Copying blob sha256:b20444ad59a0bac9dcf73ebc5b09072abfea2b7e97ca52637a738f1e7b9b6655
Copying config sha256:fd1314c30e49b98481ac2810600d7ee1ae5848f53e14998a31f0bbe3b98688f8
Writing manifest to image destination
Copying config sha256:fd1314c30e49b98481ac2810600d7ee1ae5848f53e14998a31f0bbe3b98688f8
Writing manifest to image destination
Storing signatures
Successfully pushed //image-registry.openshift-image-registry.svc:5000/test/fruit-client-sb:latest@sha256:0c57eb791d2d2a7073d0348e76153400ce551673efbc6fcae559e17a009dd127
```
