### ISSUE TITLE
the object has been modified; please apply your changes to the latest version and try again

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#15]
### Description

When a component is designed as a component + service, then the following error is raise

```
time="2018-12-03T14:59:17Z" level=info msg="### Invoking'service catalog', action 'create service' on fruit-backend-sb"
--
  | time="2018-12-03T14:59:17Z" level=info msg="#### Created service instance's 'postgresql-db' for the service/class 'dh-postgresql-apb' and plan 'dev'"
  | time="2018-12-03T14:59:17Z" level=info msg="#### Created fruit-backend-sb CRD's service component"
  | time="2018-12-03T14:59:17Z" level=error msg="Operation cannot be fulfilled on components.component.k8s.io \"fruit-backend-sb\": the object has been modified; please apply your changes to the latest version and try again"
  | time="2018-12-03T14:59:18Z" level=info msg="### Invoking'service catalog', action 'create service' on fruit-backend-sb"
  | time="2018-12-03T14:59:18Z" level=info msg="#### Created service instance's 'postgresql-db' for the service/class 'dh-postgresql-apb' and plan 'dev'"
  | time="2018-12-03T14:59:18Z" level=info msg="#### Created fruit-backend-sb CRD's service component"
  | time="2018-12-03T14:59:18Z" level=info msg="### Pipeline 'service catalog' ended ###"
  | time="2018-12-03T14:59:18Z" level=info msg="Reconciling AppService cmoulliard/fruit-backend-sb - operation created\n"
```

### Yaml resource file

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "component.k8s.io/v1alpha1"
  kind: "Component"
  metadata:
    name: "fruit-backend-sb"
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: true
    envs:
    - name: "SPRING_PROFILES_ACTIVE"
      value: "openshift-catalog"
    links:
    - kind: "Secret"
      name: "Secret to be injected as EnvVar using Service's secret"
      targetComponentName: "fruit-backend-sb"
      ref: "postgresql-db"
    services:
    - name: "postgresql-db"
      class: "dh-postgresql-apb"
      plan: "dev"
      secretName: "postgresql-db"
      parameters:
      - name: "postgresql_user"
        value: "luke"
      - name: "postgresql_password"
        value: "secret"
      - name: "postgresql_database"
        value: "my_data"
      - name: "postgresql_version"
        value: "9.6"
```
