### ISSUE TITLE
Check if openApiv3 used by k8s can handle complex types

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#39]
## Description

Check if [openApiv3 supported](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation) by k8s since 1.13 when we define CRD can handle complex types

## Example

```
validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            app:
              type: "string"
              minimum: 1
            codebase:
              type: "string"
              minimum: 1
            buildtype:
              type: "string"
              minimum: 1 
            listenport:
              type: "number"
```

**Comment by cmoulliard** [comment]
## Test 1 : Required field `app`

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.component.k8s.io
spec:
  group: component.k8s.io
  version: v1alpha1
  names:
    kind: Component
    listKind: ComponentList
    plural: components
    singular: component
    shortNames:
      - cp
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
  scope: Namespaced
  validation:
    # https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject
    openAPIV3Schema:
      required:
      - app
      properties:
        spec:
          properties:
            app:
              type: string
            runtime:
              type: string
              enum:
                - spring-boot
                - vert.x
                - thorntail
```

Output

```
The Component "example" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"component.k8s.io/v1alpha1", "kind":"Component", "metadata":map[string]interface {}{"name":"example", "namespace":"myproject", "creationTimestamp":"2019-03-04T10:20:50Z", "annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"component.k8s.io/v1alpha1\",\"kind\":\"Component\",\"metadata\":{\"annotations\":{},\"name\":\"example\",\"namespace\":\"myproject\"}}\n"}, "generation":1, "uid":"2efe75de-3e67-11e9-bae6-b2115b32cca2", "selfLink":"", "clusterName":""}}: validation failure list:
.app in body is required
```

**Comment by cmoulliard** [comment]
## Test2 - Required fields `runtime` of enum and infoitem of `name`, `value`

CR
```
apiVersion: "component.k8s.io/v1alpha1"
kind: "Component"
metadata:
  name: "example"
spec:
  app: "my-spring-boot"
  runtime: "spring-boot"
  infoitems:
    - name: hello
```

CRD
```
    openAPIV3Schema:
      properties:
        spec:
          required:
            - app
            - runtime
          properties:
            app:
              type: string
            runtime:
              type: string
              enum:
                - spring-boot
                - vert.x
                - thorntail
            infoitems:
              items:
                required:
                  - name
                  - value
                properties:
                  name:
                    type: string
                  value:
                    type: string
```

Output
```
spec.infoitems.value in body is required
```

**Comment by cmoulliard** [comment]
## Test3 - Test2 but including `buildtype`

CR
```
apiVersion: "component.k8s.io/v1alpha1"
kind: "Component"
metadata:
  name: "example"
spec:
  app: "my-spring-boot"
  runtime: "spring-boot"
  infoitems:
    - name: hello
      value: world
      object:
        - kind: envvar
          key1: JAVA_HOME
          value: /usr/local/bin
```

CRD
```
    openAPIV3Schema:
      properties:
        spec:
          required:
            - app
            - runtime
            - buildtype
          properties:
            app:
              type: string
            buildtype:
              type: string
            runtime:
              type: string
              enum:
                - spring-boot
                - vert.x
                - thorntail
            infoitems:
              items:
                required:
                  - name
                  - value
                properties:
                  name:
                    type: string
                  value:
                    type: string
                  object:
                    items:
                      required:
                        - kind
                        - key
                      properties:
                        kind:
                          type: string
                        key:
                          type: string
                        value:
                          type: string
```

Output
```
spec.infoitems.object.key in body is required
spec.buildtype in body is required
```
