### ISSUE TITLE
Convention to respect to create Component CRDs

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#48]
### Enhancement

As the secondary resources that the controller will create are coming from the information of one of the crds `Component`, `Link` or `Capability`, it is important to respect the same convention and to be sure that their `.metadata.name` field is created using the same information.

As it appears that we use sometimes the `.spec.name` field of the CRD or sometimes the `.metadata.name`, I propose then that we adopt the same convention an that we use as input the `.metadata.name` of the CRDs.

A second advantage to make this change and to remove the `.spec.name` of the CRDs is also that we will avoid to define at 2 different places the same info as it appeared that we created such yaml resources

```
- apiVersion: "devexp.runtime.redhat.com/v1alpha2"
  kind: "Link"
  metadata:
    name: "link-to-database" 
  spec:
    name: "link-to-database" // SAME INFO AS METADATA
    componentName: "fruit-backend-sb"
    kind: "Secret"
    ref: "postgresql-db"
```

With the modification, here is what we will do then

Example modified for a Capability
```
apiVersion: "devexp.runtime.redhat.com/v1alpha2"
  kind: "Capability"
  metadata:
    name: "postgresql-db"
 spec:
    // name field has been removed
    class:
    plan:
    ...
```

ServiceBinding resource created
```
//buildServiceBinding returns the service binding resource
func (r *ReconcileCapability) buildServiceBinding(s *v1alpha2.Capability) *servicecatalogv1.ServiceBinding {
	ls := r.GetAppLabels(s.Name)
	service := &servicecatalogv1.ServiceBinding{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "servicecatalog.k8s.io/v1beta1",
			Kind:       "ServiceBinding",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      s.Name, // We use HERE the .metadata field of the CRD
			Namespace: s.Namespace,
			Labels:    ls,
		},
```

Make sense: @metacosm @iocanel @aureamunoz @geoand
