### ISSUE TITLE
[Feature]: Add Build spec

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#52]
## Feature request

To switch from `dev` to `build` mode, the component operator will need some additional infos in order to fetch the project to be compiled, like also optionally the docker s2i image to be used, ...

We could rely on k8s annotations in order to configure the Tekton build task(s) responsible to perform a build using as input: github repository, github reference, ... as presented hereafter (and implemented with a previous release of the Component operator) but I think that it makes more sense if we create a `Build Spec` (if you adhere) and next that our tools : `dekorate` and `kreate` support it. WDYT @metacosm @geoand @iocanel @aureamunoz 

Example
```
app.openshift.io/git-ref: "master"
app.openshift.io/component-name: "fruit-backend-sb"
app.openshift.io/artifact-copy-args: "*.jar"
app.openshift.io/java-app-jar: "fruit-backend-sb-0.0.1-SNAPSHOT.jar"
app.openshift.io/git-dir: "fruit-backend-sb"
app.openshift.io/git-uri: "https://github.com/snowdrop/component-operator-demo.git"
app.openshift.io/runtime-image: "fruit-backend-sb"
```

Build Spec proposition
```
URI string // URI is the https Github URL repo to be cloned
Ref string // /Ref is a git reference. Optional. "master" is used by default. 
ContextDir // ContextDir is a path to subfolder in the repo. It could correspond to a maven module. By default, it is equal to "."
BaseImage // BaseImage is the image to build the project from. For s2i, the buildImage is equal to the runtimeImage
RuntimeImage // RuntimeImage is the runtime or execution image to be used to launch the container. For s2i, that will corresponds to the s2i build image
ArtifactToCopy // ArtifactToCopy is the regex of the files to be copied to the targetFolder
Targetdir // This is the s2i target directory where the resources uploaded or built will be copied
DockerFilePath // DockerfilePath is the path of the Dockerfile to be used to perform the build
SOMETHING ELSE ??
```

Questions:
- Do we need a more elaborated Git spec as defined by DevTools team [1] ?
- Should we make this `Build Spec` part of the `Component CRD Spec` ?
- Can `Ap4k` or `kreate` support the creation of the BuildSpec - git based on what they can discover within the maven project (or gradle project) ?
- Could `ap4k/dekorate` support it using the `annotationless mode` and where the user could override some values (e.g docker image or dockerfile to be used, ...) ?

[1] https://github.com/redhat-developer/devconsole-api/blob/master/pkg/apis/devconsole/v1alpha1/gitsource_types.go#L11

**Comment by metacosm** [comment]
How would that work? Does that mean that we would create a new `Build` resource that would then be referenced from the component instead of using the `DeploymentMode` field?

**Comment by cmoulliard** [comment]
> `DeploymentMode` field?

We will continue to use component > deploymentMode: build but including a build section with the info needed to configure the build process

**Comment by geoand** [comment]
So the BuildSpec would be a subsection of the CRD?

**Comment by cmoulliard** [comment]
> subsection of the CRD?

It will be a normal field as we have for Env var by example - https://github.com/snowdrop/component-operator/blob/master/pkg/apis/component/v1alpha2/component_types.go#L40

**Comment by geoand** [comment]
Yeah, that is what I meant, thanks

**Comment by cmoulliard** [comment]
Example

```
kind: "Component"
  metadata:
    labels:
      app: "fruit-backend-sb"
      version: "0.0.1-SNAPSHOT"
      group: "fruit-application"
    name: "fruit-backend-sb"
  spec:
    name: "fruit-backend-sb"
    deploymentMode: "build" // we set build
    runtime: "spring-boot"
    version: "2.1.3.RELEASE"
    exposeService: true
    build:
      uri: https://github.com/snowdrop/component-operator-demo.git
      ref: master
      contextDir: fruit-backend
    envs:
    - name: "SPRING_PROFILES_ACTIVE"
      value: "openshift-catalog"
```
