### ISSUE TITLE
Namespace is created using artifact-id and not current project

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#7]
Operator reports such error 
```
time="2018-11-15T18:08:13Z" level=info msg="### Invoking pipeline 'innerloop', action 'deploy' on fruit-client"
time="2018-11-15T18:08:13Z" level=error msg="namespaces \"fruit-client\" not found"
```
when the following CRD is applied
```
apiVersion: component.k8s.io/v1alpha1
kind: Component
metadata:
  name: fruit-client
spec:
  deployment: innerloop
  runtime: springboot # Why ? To inform the operator to use java runtime's image
  version: 1.5.16
  exposeService: true # Create a Route
```
