### ISSUE TITLE
Rename field BuildConfig.spec.type

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/component-operator#72]
In ap4k we allow the customization of `BuildConfig.spec.type` field. This field contains the image build strategy, i.e. `s2i`. This name is not very descriptive.
This is a possible configuration by application.properties file:
```
ap4k.component.name=annotationless component
ap4k.component.envs[0].name=key1
ap4k.component.envs[0].value=value1
ap4k.component.type=s2i
```
s2i is not a "type" of component.
WDYT? @cmoulliard

**Comment by cmoulliard** [comment]
The type `buildconfig` should be part of the description - `ap4k.component.type=s2i`

My proposition

```
ap4k.component.buildconfig.type=s2i

or 

ap4k:
  component:
   buildconfig:
     type: s2i
     url: https://github.com/snowdrop/component-operator-demo.git
     ref: master
     moduleDirName: fruit-backend-sb
```

Make sense @aureamunoz @metacosm @iocanel ?
