### ISSUE TITLE
Missing scc rule to create the PostgreSQL Pod

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#80]
## Issue

When the `PostgreSQL Pod` will be created by the `statefulset` resource of the KubeDB operator, then the following error will be reported if the ServiceAccount of the POD don't has at least the `Privileged` SCC

```
Error creating: pods "pod..." is forbidden: unable to validate against any security context constraint: [capabilities.add: Invalid value: "IPC_LOCK": capability may not be added capabilities.add: Invalid value: "IPC_LOCK": capability may not be added]
```

The workaround is to include the SA used by the statefulset to the SCC

Example of SCC resource including the SA used by the KubeDB operator

```
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
  name: privileged
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:admin
- system:serviceaccount:openshift-infra:build-controller
- system:serviceaccount:openshift-node:sync
- system:serviceaccount:openshift-sdn:sdn
- system:serviceaccount:management-infra:management-admin
- system:serviceaccount:management-infra:inspector-admin
- system:serviceaccount:istio-system:jaeger
- system:serviceaccount:gandrian:default
- system:serviceaccount:istio-system:istio-pilot-service-account
- system:serviceaccount:gandrian:sa-greeting
- system:serviceaccount:openshift-logging:aggregated-logging-fluentd
- system:serviceaccount:cmoullia:default
- system:serviceaccount:cmoullia:build-bot
- system:serviceaccount:demo:build-bot
- system:serviceaccount:demo:my-postgres
- system:serviceaccount:demo:postgres-db
- system:serviceaccount:test1:postgres-db
volumes:
- '*'
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:nodes
- system:masters
```

**Comment by cmoulliard** [comment]
Comment from Matt Dorn

For your OpenShift-centric Operator, your Operator can send an api call to add the build-bot user to the privileged SCC.

You can import the  `github.com/openshift/api/security/v1` package to interact with SCC endpoints.

Keep in mind that you will need to ensure that the Service Account associated with your Operator will need a ClusterRole that can interact with SCC endpoints [1].

You could also add build-bot to the existing `edit` role, although I think it would a better practice to create a custom role for this. You could define this custom role in your CSV under `permissions`.

PSP would be for plain k8s. If you are a developing an upstream-community-operator for plain k8s, there isn't any expectation that the PodSecurityPolicy AdmissionController is enabled and/or existing PSP's exist. It the PodSecurityPolicy Admission Controller happens to be enabled, you can authorize the Service Account associated with the Pod to use the privileged PSP by setting the `use` verb on it [2] [3].

[1] https://github.com/operator-framework/community-operators/blob/4493ccc514647f093e4488b423fee6cf6ea0b6df/upstream-community-operators/kubevirt/kubevirtoperator.v0.18.1.clusterserviceversion.yaml#L216-L225
[2] https://github.com/operator-framework/community-operators/blob/9dbbc2e83909c1b12fc617696f54b19816487ace/upstream-community-operators/oneagent/dynatrace-monitoring.v0.3.1.clusterseviceversion.yaml#L229-L236
[3] https://kubernetes.io/docs/concepts/policy/pod-security-policy/#authorizing-policies

**Comment by cmoulliard** [comment]
As we are struggling to get privileged scc for the pod created by Tekton or Kubedb, the workaround as reported John Strunk on the mailing list is perhaps to do that 

"It is possible to give access to the scc via a Role and skip the `oc adm ...`. This allows you to create the service account with the correct permissions from the start.
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
    resourceNames: ["privileged"]

I believe this was added in 3.10 or 3.11."

I did a test which was working using master branch and these steps with append the serviceaccount user to the SCC users list 

```
- Start operator on project test13
- oc apply -f examples/demo-v1alpha2/component-build.yml 
- Check taskRun -> `unable to validate against any security context constraint: [ca .....`
- oc delete all,sa --all

- oc apply -f -->
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: use-scc-privileged-role
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["use"]
  resourceNames: ["privileged"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: use-scc-privileged
subjects:
  - kind: ServiceAccount
    name: build-bot
roleRef:
  kind: Role
  name: use-scc-privileged-role
  apiGroup: rbac.authorization.k8s.io

- oc apply -f examples/demo-v1alpha2/component-build.yml 
- Check taskRun --> OK OK
```

@metacosm
